image:
  repository: env-test/myproject-api
  tag: "production-5a35bdb" # 2022-06-15T07:00:00Z https://circleci.com/gh/env-test/myproject-api/6

containerPort: 80

replicaCount: 2

deployment:
  env:
    normal:
      PROJECT_ENV: "production"
      MY_VARIABLE: "2"
